"use server";

import { redirect } from "next/navigation";
import { getCurrentMember } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getPlan, hotelLimit } from "@/lib/plans";

type State = { error: string | null };

const METHODS = ["url_change", "same_page", "both"] as const;
type Method = (typeof METHODS)[number];

export async function createHotel(
  _prev: State,
  formData: FormData,
): Promise<State> {
  const member = await getCurrentMember();
  if (!member) return { error: "Your session has expired — please sign in again." };

  // Enforce the plan's hotel cap (server-side source of truth).
  const limit = hotelLimit(member.agency.plan);
  if (Number.isFinite(limit)) {
    const count = await prisma.hotelClient.count({
      where: { agencyId: member.agencyId },
    });
    if (count >= limit) {
      return {
        error: `Your ${getPlan(member.agency.plan).name} plan includes up to ${limit} hotel clients. Upgrade on the Billing page to add more.`,
      };
    }
  }

  const get = (k: string) => ((formData.get(k) as string | null) ?? "").trim();
  const name = get("name");
  const websiteUrl = get("websiteUrl");
  const contactName = get("contactName");
  const contactEmail = get("contactEmail");
  const method = get("conversionMethod");
  const thankYouUrlPattern = get("thankYouUrlPattern");
  const successPhrase = get("successPhrase");
  const successSelector = get("successSelector");

  if (!name || !websiteUrl || !contactName || !contactEmail) {
    return { error: "Please fill in name, website URL, contact name, and contact email." };
  }
  if (!METHODS.includes(method as Method)) {
    return { error: "Please choose how a booking is confirmed." };
  }
  if ((method === "url_change" || method === "both") && !thankYouUrlPattern) {
    return { error: "Enter the thank-you URL pattern for redirect-based bookings." };
  }
  if ((method === "same_page" || method === "both") && !successPhrase && !successSelector) {
    return { error: "Enter a success phrase or a CSS selector for same-page bookings." };
  }

  // siteId is auto-generated by the schema's @default(cuid()). Scoped to this
  // agency via agencyId — never trust a client-supplied agency.
  const hotel = await prisma.hotelClient.create({
    data: {
      agencyId: member.agencyId,
      name,
      websiteUrl,
      contactName,
      contactEmail,
      conversionMethod: method as Method,
      thankYouUrlPattern: thankYouUrlPattern || null,
      successPhrase: successPhrase || null,
      successSelector: successSelector || null,
    },
    select: { id: true },
  });

  redirect(`/agency/hotels/${hotel.id}/setup`);
}
